//! Shell completion scripts derived from the command metadata.
//!
//! Scripts are written to standard output only; installing them (and editing
//! any shell profile) is left to the user.

use crate::commands::{CommandMeta, FlagMeta};
use std::fmt::Write as _;
use std::str::FromStr;

/// A shell with a completion generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    /// GNU Bash (3.2 or newer).
    Bash,
    /// Z shell.
    Zsh,
    /// Fish shell.
    Fish,
}

impl Shell {
    /// Every supported shell.
    pub const ALL: [Self; 3] = [Self::Bash, Self::Zsh, Self::Fish];

    /// Name as written on the command line.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Bash => "bash",
            Self::Zsh => "zsh",
            Self::Fish => "fish",
        }
    }
}

impl FromStr for Shell {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .into_iter()
            .find(|shell| shell.name() == s)
            .ok_or_else(|| format!("unsupported shell `{s}` (expected bash, zsh or fish)"))
    }
}

/// Render the completion script for `shell` from `commands` and `globals`.
#[must_use]
pub fn render(shell: Shell, commands: &[CommandMeta], globals: &[FlagMeta]) -> String {
    let nodes = flatten(commands);
    match shell {
        Shell::Bash => render_bash(commands, &nodes, globals),
        Shell::Zsh => render_zsh(commands, &nodes, globals),
        Shell::Fish => render_fish(commands, &nodes, globals),
    }
}

/// A command at a space-separated path, e.g. `services up`.
struct Node<'a> {
    path: String,
    meta: &'a CommandMeta,
}

fn flatten(commands: &[CommandMeta]) -> Vec<Node<'_>> {
    fn walk<'a>(prefix: &str, commands: &'a [CommandMeta], out: &mut Vec<Node<'a>>) {
        for meta in commands {
            let path = if prefix.is_empty() {
                meta.name.clone()
            } else {
                format!("{prefix} {}", meta.name)
            };
            out.push(Node {
                path: path.clone(),
                meta,
            });
            walk(&path, &meta.subcommands, out);
        }
    }
    let mut out = Vec::new();
    walk("", commands, &mut out);
    // Deepest first so longer paths match before their parents.
    out.sort_by_key(|node| std::cmp::Reverse(node.path.split(' ').count()));
    out
}

/// How the value of a flag is completed.
enum ValueKind {
    File,
    Dir,
    Other,
}

fn value_kind(flag: &FlagMeta) -> Option<ValueKind> {
    flag.arg_name.as_deref().map(|arg| match arg {
        "PATH" | "FILE" => ValueKind::File,
        "DIR" => ValueKind::Dir,
        _ => ValueKind::Other,
    })
}

/// All flags of every command plus the globals, deduplicated by name.
fn all_flags<'a>(nodes: &[Node<'a>], globals: &'a [FlagMeta]) -> Vec<&'a FlagMeta> {
    let mut out: Vec<&FlagMeta> = Vec::new();
    for flag in globals
        .iter()
        .chain(nodes.iter().flat_map(|n| n.meta.flags.iter()))
    {
        if !out.iter().any(|f| f.name == flag.name) {
            out.push(flag);
        }
    }
    out
}

fn flag_spellings(flag: &FlagMeta) -> Vec<String> {
    let mut out = vec![flag.name.clone()];
    if let Some(short) = flag.short {
        out.push(format!("-{short}"));
    }
    out
}

fn value_flag_spellings(flags: &[&FlagMeta], kind: Option<fn(&ValueKind) -> bool>) -> Vec<String> {
    flags
        .iter()
        .filter(|f| match (value_kind(f), kind) {
            (Some(k), Some(pred)) => pred(&k),
            (Some(_), None) => true,
            (None, _) => false,
        })
        .flat_map(|f| flag_spellings(f))
        .collect()
}

fn names(flags: &[FlagMeta]) -> Vec<String> {
    flags.iter().flat_map(flag_spellings).collect()
}

/// Single-quote `s` for POSIX shells.
fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

fn render_bash(commands: &[CommandMeta], nodes: &[Node<'_>], globals: &[FlagMeta]) -> String {
    let flags = all_flags(nodes, globals);
    let value_flags = value_flag_spellings(&flags, None).join("|");
    let file_flags = value_flag_spellings(&flags, Some(|k| matches!(k, ValueKind::File)));
    let dir_flags = value_flag_spellings(&flags, Some(|k| matches!(k, ValueKind::Dir)));
    let global_words = names(globals);

    let mut s = String::new();
    s.push_str(
        "# bash completion for siderite (generated by `siderite completions bash`)\n\
         _siderite() {\n\
         \x20   local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n\
         \x20   local prev=\"\"\n\
         \x20   [ \"$COMP_CWORD\" -gt 0 ] && prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\
         \x20   if [ \"$cur\" = \"=\" ]; then\n\
         \x20       cur=\"\"\n\
         \x20   elif [ \"$prev\" = \"=\" ] && [ \"$COMP_CWORD\" -gt 1 ]; then\n\
         \x20       prev=\"${COMP_WORDS[COMP_CWORD-2]}\"\n\
         \x20   fi\n\
         \x20   case \"$prev\" in\n",
    );
    if !file_flags.is_empty() {
        let _ = writeln!(
            s,
            "        {}) COMPREPLY=( $(compgen -f -- \"$cur\") ); return 0 ;;",
            file_flags.join("|")
        );
    }
    if !dir_flags.is_empty() {
        let _ = writeln!(
            s,
            "        {}) COMPREPLY=( $(compgen -d -- \"$cur\") ); return 0 ;;",
            dir_flags.join("|")
        );
    }
    if !value_flags.is_empty() {
        let _ = writeln!(s, "        {value_flags}) COMPREPLY=(); return 0 ;;");
    }
    s.push_str(
        "    esac\n\
         \x20   local cmd_path=\"\" skip=0 w i=1\n\
         \x20   while [ \"$i\" -lt \"$COMP_CWORD\" ]; do\n\
         \x20       w=\"${COMP_WORDS[i]}\"\n\
         \x20       i=$((i + 1))\n\
         \x20       if [ \"$skip\" = 1 ]; then\n\
         \x20           [ \"$w\" = \"=\" ] || skip=0\n\
         \x20           continue\n\
         \x20       fi\n\
         \x20       case \"$w\" in\n",
    );
    if !value_flags.is_empty() {
        let _ = writeln!(s, "            {value_flags}) skip=1 ;;");
    }
    s.push_str(
        "            -*|=) ;;\n\
         \x20           *) cmd_path=\"$cmd_path $w\" ;;\n\
         \x20       esac\n\
         \x20   done\n\
         \x20   local words\n\
         \x20   case \"$cmd_path\" in\n",
    );
    let mut top: Vec<String> = commands.iter().map(|c| c.name.clone()).collect();
    top.extend(global_words.iter().cloned());
    let _ = writeln!(s, "        \"\") words={} ;;", sh_quote(&top.join(" ")));
    for node in nodes {
        let mut words: Vec<String> = node
            .meta
            .subcommands
            .iter()
            .map(|c| c.name.clone())
            .collect();
        words.extend(node.meta.values.iter().cloned());
        words.extend(names(&node.meta.flags));
        words.extend(global_words.iter().cloned());
        let _ = writeln!(
            s,
            "        \" {}\") words={} ;;",
            node.path,
            sh_quote(&words.join(" "))
        );
    }
    for node in nodes {
        let mut words = names(&node.meta.flags);
        words.extend(global_words.iter().cloned());
        let _ = writeln!(
            s,
            "        \" {} \"*) words={} ;;",
            node.path,
            sh_quote(&words.join(" "))
        );
    }
    let _ = writeln!(
        s,
        "        *) words={} ;;",
        sh_quote(&global_words.join(" "))
    );
    s.push_str(
        "    esac\n\
         \x20   COMPREPLY=( $(compgen -W \"$words\" -- \"$cur\") )\n\
         \x20   return 0\n\
         }\n\
         complete -F _siderite siderite\n",
    );
    s
}

/// `name:description` entry for zsh `_describe`.
fn zsh_item(name: &str, desc: &str) -> String {
    sh_quote(&format!("{}:{desc}", name.replace(':', r"\:")))
}

fn zsh_flag_items(flags: &[FlagMeta]) -> Vec<String> {
    flags
        .iter()
        .flat_map(|f| {
            flag_spellings(f)
                .into_iter()
                .map(|name| zsh_item(&name, &f.description))
        })
        .collect()
}

fn render_zsh(commands: &[CommandMeta], nodes: &[Node<'_>], globals: &[FlagMeta]) -> String {
    let flags = all_flags(nodes, globals);
    let value_flags = value_flag_spellings(&flags, None).join("|");
    let file_flags = value_flag_spellings(&flags, Some(|k| matches!(k, ValueKind::File)));
    let dir_flags = value_flag_spellings(&flags, Some(|k| matches!(k, ValueKind::Dir)));
    let global_items = zsh_flag_items(globals).join(" ");

    let mut s = String::new();
    s.push_str(
        "#compdef siderite\n\
         # zsh completion for siderite (generated by `siderite completions zsh`)\n\
         _siderite() {\n\
         \x20   local cur=\"${words[CURRENT]}\" prev=\"${words[CURRENT-1]}\" flag=\"\"\n\
         \x20   if [[ \"$cur\" == --*=* ]]; then\n\
         \x20       flag=\"${cur%%=*}\"\n\
         \x20       compset -P '*='\n\
         \x20   elif (( CURRENT > 2 )); then\n\
         \x20       flag=\"$prev\"\n\
         \x20   fi\n\
         \x20   case \"$flag\" in\n",
    );
    if !file_flags.is_empty() {
        let _ = writeln!(s, "        {}) _files; return ;;", file_flags.join("|"));
    }
    if !dir_flags.is_empty() {
        let _ = writeln!(s, "        {}) _files -/; return ;;", dir_flags.join("|"));
    }
    if !value_flags.is_empty() {
        let _ = writeln!(s, "        {value_flags}) return ;;");
    }
    s.push_str(
        "    esac\n\
         \x20   local cmd_path=\"\" skip=0 w i\n\
         \x20   for (( i = 2; i < CURRENT; i++ )); do\n\
         \x20       w=\"${words[i]}\"\n\
         \x20       if (( skip )); then skip=0; continue; fi\n\
         \x20       case \"$w\" in\n",
    );
    if !value_flags.is_empty() {
        let _ = writeln!(s, "            {value_flags}) skip=1 ;;");
    }
    let _ = writeln!(
        s,
        "            -*) ;;\n\
         \x20           *) cmd_path=\"$cmd_path $w\" ;;\n\
         \x20       esac\n\
         \x20   done\n\
         \x20   local -a subs vals opts\n\
         \x20   opts=({global_items})\n\
         \x20   case \"$cmd_path\" in"
    );
    let top: Vec<String> = commands
        .iter()
        .map(|c| zsh_item(&c.name, &c.summary))
        .collect();
    let _ = writeln!(s, "        \"\") subs=({}) ;;", top.join(" "));
    for node in nodes {
        let subs: Vec<String> = node
            .meta
            .subcommands
            .iter()
            .map(|c| zsh_item(&c.name, &c.summary))
            .collect();
        let vals: Vec<String> = node.meta.values.iter().map(|v| sh_quote(v)).collect();
        let _ = writeln!(
            s,
            "        \" {}\") subs=({}); vals=({}); opts+=({}) ;;",
            node.path,
            subs.join(" "),
            vals.join(" "),
            zsh_flag_items(&node.meta.flags).join(" ")
        );
    }
    for node in nodes {
        let _ = writeln!(
            s,
            "        \" {} \"*) opts+=({}) ;;",
            node.path,
            zsh_flag_items(&node.meta.flags).join(" ")
        );
    }
    s.push_str(
        "    esac\n\
         \x20   if [[ \"$cur\" == -* ]]; then\n\
         \x20       _describe -t options 'option' opts\n\
         \x20   else\n\
         \x20       if (( ${#subs} )); then _describe -t commands 'command' subs; fi\n\
         \x20       if (( ${#vals} )); then compadd -a vals; fi\n\
         \x20   fi\n\
         }\n\
         if [ \"$funcstack[1]\" = \"_siderite\" ]; then\n\
         \x20   _siderite \"$@\"\n\
         else\n\
         \x20   compdef _siderite siderite\n\
         fi\n",
    );
    s
}

/// Single-quote `s` for fish.
fn fish_quote(s: &str) -> String {
    format!("'{}'", s.replace('\\', r"\\").replace('\'', r"\'"))
}

fn fish_flag_line(condition: Option<&str>, flag: &FlagMeta) -> String {
    let mut line = String::from("complete -c siderite");
    if let Some(cond) = condition {
        let _ = write!(line, " -n {}", fish_quote(cond));
    }
    if let Some(long) = flag.name.strip_prefix("--") {
        let _ = write!(line, " -l {long}");
    }
    if let Some(short) = flag.short {
        let _ = write!(line, " -s {short}");
    }
    match value_kind(flag) {
        Some(ValueKind::File) => line.push_str(" -r -F"),
        Some(ValueKind::Dir) => line.push_str(" -x -a '(__fish_complete_directories)'"),
        Some(ValueKind::Other) => line.push_str(" -x"),
        None => {}
    }
    let _ = write!(line, " -d {}", fish_quote(&flag.description));
    line
}

fn render_fish(commands: &[CommandMeta], nodes: &[Node<'_>], globals: &[FlagMeta]) -> String {
    let flags = all_flags(nodes, globals);
    let value_flags: Vec<String> = value_flag_spellings(&flags, None)
        .iter()
        .map(|f| fish_quote(f))
        .collect();

    let mut s = String::new();
    s.push_str(
        "# fish completion for siderite (generated by `siderite completions fish`)\n\
         function __siderite_path\n\
         \x20   set -l toks (commandline -opc)\n\
         \x20   set -e toks[1]\n\
         \x20   set -l cmd_path\n\
         \x20   set -l skip 0\n\
         \x20   for t in $toks\n\
         \x20       if test $skip = 1\n\
         \x20           set skip 0\n\
         \x20           continue\n\
         \x20       end\n\
         \x20       switch $t\n",
    );
    if !value_flags.is_empty() {
        let _ = writeln!(
            s,
            "            case {}\n                set skip 1",
            value_flags.join(" ")
        );
    }
    s.push_str(
        "            case '-*'\n\
         \x20           case '*'\n\
         \x20               set -a cmd_path $t\n\
         \x20       end\n\
         \x20   end\n\
         \x20   string join ' ' -- $cmd_path\n\
         end\n\
         function __siderite_at\n\
         \x20   set -l p (__siderite_path)\n\
         \x20   test \"$p\" = \"$argv[1]\"\n\
         end\n\
         function __siderite_in\n\
         \x20   set -l p (__siderite_path)\n\
         \x20   test \"$p\" = \"$argv[1]\"; or string match -q -- \"$argv[1] *\" \"$p\"\n\
         end\n\
         complete -c siderite -f\n",
    );
    for flag in globals {
        let _ = writeln!(s, "{}", fish_flag_line(None, flag));
    }
    for cmd in commands {
        let _ = writeln!(
            s,
            "complete -c siderite -n '__siderite_at \"\"' -a {} -d {}",
            cmd.name,
            fish_quote(&cmd.summary)
        );
    }
    for node in nodes {
        let at = format!("__siderite_at '{}'", node.path);
        for sub in &node.meta.subcommands {
            let _ = writeln!(
                s,
                "complete -c siderite -n {} -a {} -d {}",
                fish_quote(&at),
                sub.name,
                fish_quote(&sub.summary)
            );
        }
        if !node.meta.values.is_empty() {
            let _ = writeln!(
                s,
                "complete -c siderite -n {} -a {}",
                fish_quote(&at),
                fish_quote(&node.meta.values.join(" "))
            );
        }
        let within = format!("__siderite_in '{}'", node.path);
        for flag in &node.meta.flags {
            let _ = writeln!(s, "{}", fish_flag_line(Some(&within), flag));
        }
    }
    s
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;
    use crate::commands::{
        LiveAccess, MutationKind, OutputMode, ProjectRequirement, command_catalog, global_flags,
    };
    use std::path::Path;
    use std::process::Command;

    fn cmd(name: &str, summary: &str, flags: Vec<FlagMeta>, subs: Vec<CommandMeta>) -> CommandMeta {
        CommandMeta {
            name: name.into(),
            summary: summary.into(),
            description: String::new(),
            usage: String::new(),
            category: "test".into(),
            values: vec![],
            subcommands: subs,
            project_requirement: ProjectRequirement::None,
            mutation: MutationKind::None,
            live_access: LiveAccess::None,
            output_modes: vec![OutputMode::Text],
            flags,
        }
    }

    /// Synthetic catalog with two levels of nesting and a fixed value set.
    fn fixture() -> Vec<CommandMeta> {
        let up = cmd(
            "up",
            "Start services",
            vec![FlagMeta::flag("--wait", None, "Wait until ready")],
            vec![],
        );
        let down = cmd("down", "Stop services", vec![], vec![]);
        let mut shells = cmd("completions", "Print a script", vec![], vec![]);
        shells.values = vec!["bash".into(), "zsh".into(), "fish".into()];
        vec![
            cmd(
                "routes",
                "List the app's routes",
                vec![FlagMeta::flag("--json", None, "JSON")],
                vec![],
            ),
            cmd("services", "Manage services: local", vec![], vec![up, down]),
            shells,
        ]
    }

    fn shell_available(name: &str) -> bool {
        Command::new(name)
            .arg("-c")
            .arg("exit 0")
            .status()
            .is_ok_and(|s| s.success())
    }

    fn temp_script(tag: &str, body: &str) -> std::path::PathBuf {
        let dir =
            std::env::temp_dir().join(format!("siderite-completions-{tag}-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("script");
        std::fs::write(&path, body).unwrap();
        path
    }

    fn run_shell(shell: &str, script: &Path, driver: &str) -> String {
        let out = Command::new(shell)
            .arg("-c")
            .arg(format!(". '{}'\n{driver}", script.display()))
            .output()
            .unwrap();
        assert!(
            out.status.success(),
            "{shell} failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8(out.stdout).unwrap()
    }

    /// Words offered by the bash script for `line` (cursor at its end).
    fn bash_complete(script: &Path, words: &[&str]) -> Vec<String> {
        let quoted: Vec<String> = words.iter().map(|w| sh_quote(w)).collect();
        let driver = format!(
            "COMP_WORDS=({})\nCOMP_CWORD={}\n_siderite\nfor w in \"${{COMPREPLY[@]}}\"; do echo \"$w\"; done",
            quoted.join(" "),
            words.len() - 1
        );
        let out = run_shell("bash", script, &driver);
        out.lines().map(str::to_owned).collect()
    }

    #[test]
    fn shell_names_round_trip() {
        for shell in Shell::ALL {
            assert_eq!(shell.name().parse::<Shell>().unwrap(), shell);
        }
        assert!("powershell".parse::<Shell>().is_err());
    }

    #[test]
    fn catalog_names_are_shell_safe() {
        let catalog = command_catalog();
        for node in flatten(&catalog) {
            for word in node.path.split(' ') {
                assert!(
                    word.chars().all(|c| c.is_ascii_lowercase() || c == '-'),
                    "{word}"
                );
            }
        }
    }

    #[test]
    fn scripts_cover_every_catalog_command() {
        let catalog = command_catalog();
        for shell in Shell::ALL {
            let script = render(shell, &catalog, &global_flags());
            for c in &catalog {
                assert!(
                    script.contains(&c.name),
                    "{} missing {}",
                    shell.name(),
                    c.name
                );
            }
            assert!(script.contains("manifest-path"));
        }
    }

    #[test]
    fn apostrophes_are_quoted() {
        let fixture = fixture();
        let zsh = render(Shell::Zsh, &fixture, &[]);
        assert!(zsh.contains(r"'routes:List the app'\''s routes'"));
        let fish = render(Shell::Fish, &fixture, &[]);
        assert!(fish.contains(r"-d 'List the app\'s routes'"));
        // Descriptions do not appear in bash scripts.
        assert!(!render(Shell::Bash, &fixture, &[]).contains("app's"));
    }

    #[test]
    fn zsh_escapes_colons_in_names_only() {
        assert_eq!(zsh_item("a:b", "x: y"), r"'a\:b:x: y'");
    }

    #[test]
    fn fish_nested_conditions() {
        let fish = render(Shell::Fish, &fixture(), &global_flags());
        assert!(fish.contains("complete -c siderite -n '__siderite_at \\'services\\'' -a up"));
        assert!(fish.contains("-n '__siderite_in \\'services up\\'' -l wait"));
        assert!(fish.contains("-a 'bash zsh fish'"));
        assert!(fish.contains("-l manifest-path -r -F"));
        assert!(fish.contains("-l package -s p -x"));
    }

    #[test]
    fn bash_completes_commands_nested_and_values() {
        if !shell_available("bash") {
            return;
        }
        let script = temp_script("bash", &render(Shell::Bash, &fixture(), &global_flags()));
        let top = bash_complete(&script, &["siderite", ""]);
        assert!(top.contains(&"services".to_owned()));
        assert!(top.contains(&"--manifest-path".to_owned()));
        assert_eq!(
            bash_complete(&script, &["siderite", "services", ""])
                .iter()
                .filter(|w| !w.starts_with('-'))
                .collect::<Vec<_>>(),
            ["up", "down"]
        );
        assert_eq!(
            bash_complete(&script, &["siderite", "services", "up", "--w"]),
            ["--wait"]
        );
        assert_eq!(
            bash_complete(&script, &["siderite", "completions", "z"]),
            ["zsh"]
        );
        // The value already chosen is not offered again.
        assert!(
            bash_complete(&script, &["siderite", "completions", "zsh", ""])
                .iter()
                .all(|w| w.starts_with('-'))
        );
    }

    #[test]
    fn bash_skips_flag_values() {
        if !shell_available("bash") {
            return;
        }
        let script = temp_script(
            "bash-values",
            &render(Shell::Bash, &fixture(), &global_flags()),
        );
        // `-p demo` is a flag and value, not a command.
        assert_eq!(
            bash_complete(&script, &["siderite", "-p", "demo", "services", "d"]),
            ["down"]
        );
        // COMP_WORDBREAKS splits `--manifest-path=x` into three words.
        assert_eq!(
            bash_complete(
                &script,
                &[
                    "siderite",
                    "--manifest-path",
                    "=",
                    "Cargo.toml",
                    "services",
                    "u"
                ]
            ),
            ["up"]
        );
        // Flags taking non-path values offer nothing.
        assert!(bash_complete(&script, &["siderite", "--bin", ""]).is_empty());
        // Path-valued flags complete files, also after `=`.
        let dir = script.parent().unwrap().display().to_string();
        let file = script.display().to_string();
        assert_eq!(
            bash_complete(
                &script,
                &["siderite", "--manifest-path", &format!("{dir}/scr")]
            ),
            std::slice::from_ref(&file)
        );
        assert_eq!(
            bash_complete(
                &script,
                &["siderite", "--manifest-path", "=", &format!("{dir}/scr")]
            ),
            [file]
        );
    }

    #[test]
    fn real_catalog_bash_script_completes_completions_values() {
        if !shell_available("bash") {
            return;
        }
        let script = temp_script(
            "bash-real",
            &render(Shell::Bash, &command_catalog(), &global_flags()),
        );
        assert_eq!(
            bash_complete(&script, &["siderite", "completions", "f"]),
            ["fish"]
        );
        assert_eq!(
            bash_complete(&script, &["siderite", "makemigrations", "--e"]),
            ["--empty"]
        );
    }

    /// Run the zsh function with `compadd`, `_describe`, `_files` and
    /// `compset` stubbed to print what would be offered.
    fn zsh_complete(script: &Path, words: &[&str]) -> Vec<String> {
        let quoted: Vec<String> = words.iter().map(|w| sh_quote(w)).collect();
        let driver = format!(
            "compadd() {{ [ \"$1\" = -a ] && print -l -- ${{(P)2}}; }}\n\
             _describe() {{ local -a items; items=(\"${{(@P)4}}\"); \
             [ \"$PATH\" = \"$SAVED_PATH\" ] || print PATH-CLOBBERED; \
             for it in $items; do print -- \"${{it%%:*}}\"; done; }}\n\
             _files() {{ print -- \"<files$*>\"; }}\n\
             compset() {{ cur=\"${{cur#*=}}\"; }}\n\
             SAVED_PATH=\"$PATH\"\nwords=({})\nCURRENT={}\n_siderite",
            quoted.join(" "),
            words.len()
        );
        let out = run_shell("zsh", script, &driver);
        out.lines().map(str::to_owned).collect()
    }

    #[test]
    fn zsh_script_parses_and_completes_nested() {
        if !shell_available("zsh") {
            return;
        }
        let body = format!(
            "compdef() {{ :; }}\n{}",
            render(Shell::Zsh, &fixture(), &global_flags())
        );
        let script = temp_script("zsh", &body);
        let check = Command::new("zsh").arg("-n").arg(&script).status().unwrap();
        assert!(check.success());

        let top = zsh_complete(&script, &["siderite", ""]);
        assert!(top.contains(&"services".to_owned()), "{top:?}");
        assert_eq!(
            zsh_complete(&script, &["siderite", "-p", "demo", "services", ""]),
            ["up", "down"]
        );
        assert!(
            zsh_complete(&script, &["siderite", "services", "up", "--"])
                .contains(&"--wait".to_owned())
        );
        assert_eq!(
            zsh_complete(&script, &["siderite", "completions", ""]),
            ["bash", "zsh", "fish"]
        );
        assert_eq!(
            zsh_complete(&script, &["siderite", "--migrations-dir", ""]),
            ["<files-/>"]
        );
        assert_eq!(
            zsh_complete(&script, &["siderite", "--manifest-path=Ca"]),
            ["<files>"]
        );
    }

    #[test]
    fn fish_script_parses_when_fish_is_installed() {
        if !shell_available("fish") {
            return;
        }
        let script = temp_script(
            "fish",
            &render(Shell::Fish, &command_catalog(), &global_flags()),
        );
        let check = Command::new("fish")
            .arg("-n")
            .arg(&script)
            .status()
            .unwrap();
        assert!(check.success());
    }
}
