//! The `Dump` implementation generated by `derive(Schema)`.
//!
//! Named-field structs are dumped field by field: every non-skipped,
//! non-excluded field is dumped through its own `Dump` (so nested models keep
//! their computed fields), passed through the field serializer, filtered by
//! the dump options and inserted under its serde key. Computed fields and the
//! model serializer follow. Newtypes delegate to their inner value; every
//! other shape is plain Serde output plus the options.
//!
//! The implementation is always emitted but guarded by higher-ranked bounds
//! (`for<'a> T: Serialize`, `for<'a> Field: Dump`): the impl only *applies*
//! when the type is `Serialize` and its fields are `Dump`, so input-only
//! types that derive `Schema` without `Serialize` still compile. Use
//! `#[schema(no_dump)]` to opt out explicitly.

use crate::attrs::model::Container;
use crate::attrs::plan::{FieldPlan, resolve_named, resolve_unnamed};
use crate::diag::Errors;
use crate::probe::Hooks;
use proc_macro2::TokenStream;
use quote::quote;
use syn::{Data, DeriveInput, Fields, Type, WherePredicate, parse_quote};

pub fn expand(input: &DeriveInput, container: &Container, hooks: Hooks) -> TokenStream {
    // Diagnostics were already reported by the Schema expansion.
    let mut sink = Errors::default();
    let ident = &input.ident;
    let (_, ty_generics, _) = input.generics.split_for_impl();
    let mut predicates: Vec<WherePredicate> = vec![parse_quote! {
        for<'__a> #ident #ty_generics: ::siderite::__private::serde::Serialize
    }];
    if hooks == Hooks::Direct {
        predicates
            .push(parse_quote!(for<'__a> #ident #ty_generics: ::siderite::validation::ModelHooks));
    }
    let mut stream = TokenStream::new();
    let body = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => {
                let plans = resolve_named(
                    fields,
                    container.serde.rename_all,
                    container.serde.default.is_some(),
                    &[],
                    &mut sink,
                );
                stream = super::stream::named(&plans, hooks);
                named_body(&plans, container, hooks, &mut predicates)
            }
            Fields::Unnamed(fields) => {
                let elements = resolve_unnamed(fields, &mut sink);
                match elements.as_slice() {
                    [element] => {
                        let ty = element.ty;
                        predicates.push(dump_bound(ty));
                        quote!(::siderite::validation::Dump::dump(&self.0, opts))
                    }
                    _ => TokenStream::new(),
                }
            }
            Fields::Unit => TokenStream::new(),
        },
        Data::Enum(_) | Data::Union(_) => TokenStream::new(),
    };

    let mut generics = input.generics.clone();
    generics.make_where_clause().predicates.extend(predicates);
    let (impl_generics, ty_generics, where_clause) = generics.split_for_impl();
    let validation = quote!(::siderite::validation);
    let method = if body.is_empty() {
        TokenStream::new()
    } else {
        quote! {
            #[allow(unused_mut, unused_variables, clippy::needless_borrow)]
            fn dump(&self, opts: &#validation::DumpOptions)
                -> ::core::result::Result<
                    ::siderite::__private::serde_json::Value,
                    #validation::DumpError,
                >
            {
                #body
            }
        }
    };
    quote! {
        impl #impl_generics #validation::Dump for #ident #ty_generics #where_clause {
            #method
            #stream
        }
    }
}

fn dump_bound(ty: &Type) -> WherePredicate {
    parse_quote!(for<'__a> #ty: ::siderite::validation::Dump)
}

fn named_body(
    plans: &[FieldPlan<'_>],
    container: &Container,
    hooks: Hooks,
    predicates: &mut Vec<WherePredicate>,
) -> TokenStream {
    let mut stmts = Vec::new();
    for plan in plans.iter().filter(|p| p.written && !p.options.exclude) {
        predicates.push(dump_bound(plan.ty));
        stmts.push(field_stmt(plan, container, hooks, predicates));
    }
    let computed = hooks.computed_fields();
    let model = hooks.serialize_model(quote! {
        ::siderite::__private::serde_json::Value::Object(__map)
    });
    quote! {
        let mut __map = ::siderite::__private::serde_json::Map::new();
        #(#stmts)*
        #computed
        #model
    }
}

fn field_stmt(
    plan: &FieldPlan<'_>,
    container: &Container,
    hooks: Hooks,
    predicates: &mut Vec<WherePredicate>,
) -> TokenStream {
    let validation = quote!(::siderite::validation);
    let (ident, ty, key) = (plan.ident, plan.ty, &plan.key);
    let is_default = default_check(plan, container, predicates);
    let serialize = hooks.serialize_field(&plan.rust_name, quote!(__value));
    let inner = quote! {
        if let ::core::option::Option::Some(__child) = opts.for_field(#key) {
            let __value = <#ty as #validation::Dump>::dump(&self.#ident, &__child)?;
            let __is_default = #is_default;
            let __value = #serialize;
            if !__is_default && !opts.drops_value(&__value) {
                __map.insert(::std::string::ToString::to_string(#key), __value);
            }
        }
    };
    match &plan.serde.skip_serializing_if {
        Some(path) => quote!(if !#path(&self.#ident) { #inner }),
        None => inner,
    }
}

/// Expression: does the dumped `__value` equal the field's default?
///
/// Precedence: `#[field(default)]`, the field's serde default, then the
/// container's serde default. `false` when there is no known default.
fn default_check(
    plan: &FieldPlan<'_>,
    container: &Container,
    predicates: &mut Vec<WherePredicate>,
) -> TokenStream {
    use crate::attrs::field::DefaultSpec;
    use crate::attrs::serde::SerdeDefault;
    let validation = quote!(::siderite::validation);
    let (ident, ty) = (plan.ident, plan.ty);
    let typed = |value: TokenStream| {
        quote! {
            opts.exclude_defaults && {
                let __default: #ty = #value;
                __value == <#ty as #validation::Dump>::dump(&__default, &__child)?
            }
        }
    };
    let mut from_serde = |default: &SerdeDefault| match default {
        SerdeDefault::Trait => {
            predicates.push(parse_quote!(for<'__a> #ty: ::core::default::Default));
            typed(quote!(<#ty as ::core::default::Default>::default()))
        }
        SerdeDefault::Path(path) => typed(quote!(#path())),
    };
    match (
        &plan.options.default,
        &plan.serde.default,
        &container.serde.default,
    ) {
        (Some(DefaultSpec::Expr(syn::Expr::Lit(lit))), _, _)
            if matches!(lit.lit, syn::Lit::Str(_)) =>
        {
            quote!(opts.exclude_defaults && __value == ::siderite::__private::json!(#lit))
        }
        (Some(DefaultSpec::Expr(expr)), _, _) => typed(quote!(#expr)),
        (Some(DefaultSpec::Factory(path)), _, _) => typed(quote!(#path())),
        (None, Some(default), _) => from_serde(default),
        (None, None, Some(container_default)) => {
            let source = match container_default {
                SerdeDefault::Trait => {
                    predicates.push(parse_quote!(for<'__a> Self: ::core::default::Default));
                    quote!(<Self as ::core::default::Default>::default())
                }
                SerdeDefault::Path(path) => quote!(#path()),
            };
            quote! {
                opts.exclude_defaults && {
                    let __container: Self = #source;
                    __value == <#ty as #validation::Dump>::dump(&__container.#ident, &__child)?
                }
            }
        }
        (None, None, None) => quote!(false),
    }
}
